### ISSUE TITLE
[data_centre] notifications and subscriptions

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/strands_utils#54]
The idea is to implement a notification scheme that allows people to subscribe to changes to the data centre. This is following ideas of CAST and the Active Memory approach developed by @hawesie and @marc-hanheide in previous projects. The idea would be that components can subscribe e.g. using a command like this:
`subscribe(Operation op, BSON query, String collection)`
with `op` being either `DELETE`, `UPDATE`, or `ADD`; `query` being a mongodb query document to match any events against; and `collection` defining the collection to monitor. We could then send out such notification on appropriately named ROS topics with a defined message indication again operation, matched query, the mongo object id, and the collection, plus the actual content in JSON. This is to be discussed in detail at the data_centre task force meeting with @cburbridge and others.

**Comment by hawesie** [comment]
Some mongodb prior art:
- http://stackoverflow.com/questions/10014839/get-notification-for-changed-documents-in-mongodb
- https://jira.mongodb.org/browse/SERVER-5042
- http://www.littlelostmanuals.com/2011/10/mongodb-rabbitmq-continuous-query.html
- http://appinno.wordpress.com/2012/03/29/mongodb-notification-using-zeromq/

**Comment by hawesie** [comment]
An alternative approach would be to add/update all db entries via ROS topics and just subscribe to them.

**Comment by marc-hanheide** [comment]
yes, kind of... but the really interesting bit is the filtering via `query`. That would allow content-based filtering, e.g. to only get notified if, e.g., the robot saw something new in a specific area (having a spatial query). Thanks for the links. I knew some of these already but not all of them.

**Comment by hawesie** [comment]
On 11 Dec 2013, at 13:46, Marc Hanheide notifications@github.com wrote:

> yes, kind of... but the really interesting bit is the filtering via query. That would allow content-based filtering, e.g. to only get notified if, e.g., the robot saw something new in a specific area (having a spatial query). Thanks for the links. I knew some of these already but not all of them.

I think there are interesting trade-offs here. If we go via the database then we get a standard language (JSON) but the associated cost of translation into and out of this. If we are constantly creating different arbitrary queries then I think this could be the way to go. However, if we end up just instantiation a reasonable number with a few different parameters, then the ROS-native approach may be better, with queries instantiated as custom subscriber. Either way, getting cross-topic queries right (e.g. object x spotted when robot is location y) will definitely be a challenge due to different update rates.
